{{- if .Values.openshift.createSecurityContextConstraint -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "llama3_1_70b_instruct_4bit.fullname" . }}-anyuid-scc
rules:
  - verbs:
      - use
    resources:
      - securitycontextconstraints
    resourceNames:
      - anyuid
      - nvidia-mig-manager
    apiGroups:
      - security.openshift.io
{{- end }}
