apiVersion: v1
kind: Service
metadata:
  name: {{ include "llama3_1_70b_instruct_4bit.fullname" . }}
  labels:
    {{- include "llama3_1_70b_instruct_4bit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "llama3_1_70b_instruct_4bit.selectorLabels" . | nindent 4 }}
