{{- if .Values.openshift.createRoute }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
{{- include "nim-embed.labels" . | nindent 4 }}
  name: {{ include "nim-embed.fullname" . }}
  annotations:
    haproxy.router.openshift.io/balance: roundrobin
spec:
  port:
    targetPort: {{ .Values.service.port }}
  to:
    kind: Service
    name: {{ include "nim-embed.fullname" . }}
{{- end }}