apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ngcSecret.name }}
data:
  ngc_api_key: {{ .Values.ngcSecret.apiKey | toString | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ (first .Values.imagePullSecrets).name }}
  labels:
    {{- include "nim-embed.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "nim-embed.generatedImagePullSecret" . }}